### ISSUE TITLE
Same article created multiple times

### ISSUE THREAD

**Issue by sanya-kenneth** [andela/ah-backend-invictus#20]
When I attempt to create an article am able to create the same article with the same title, description and body multiple times...

**Comment by KabohaJeanMark** [comment]
Hey @sanya-kenneth. I understand your concern.
What makes the article unique is the slug generated from its title and adding a unique string to it always. 
This is also how Medium works. We can all write the same title for a story such as "Onboarding onto a large codebase".
However, when it comes to searching for it if you look at the URL present on the top of your page, that is the slug. it consists of the article title in lower case with slashes between the spaces and a string at the end. You can try this out on Medium.
